---
name: Deployment
permissions: {}

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - hotfix/stage
      - hotfix/production
    tags:
      - v20[2-9][0-9][0-1][0-9][0-3][0-9]-[0-9][0-9]-rc
      - v20[2-9][0-9][0-1][0-9][0-3][0-9]-[0-9][0-9]

env:
  AWS_REGION: us-east-1

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        shell: bash -leo pipefail {0}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"
      # kics-scan ignore-block
      - name: Install runtimes
        uses: ./.github/actions/runtime

      # kics-scan ignore-block
      - name: Set environment variables
        uses: ./.github/actions/env

      # kics-scan ignore-block
      - name: Build the project
        uses: ./.github/actions/build
        with:
          environment: ${ENVIRONMENT}

      # kics-scan ignore-block
      - name: Deploy to AWS Lambda
        uses: ./.github/actions/deploy
        with:
          environment: ${ENVIRONMENT}
          aws_access_id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ env.AWS_REGION }}
